### ISSUE TITLE
No long term statistics

### ISSUE THREAD

**Issue by sophof** [guillaumelamirand/docker-monitor#4]
Hi, Thanks for forking this component, the original doesn't appear to be active anymore. Would it be possible to support long term statistics by setting the `state_class`?

To give an example, this is all I had to do via a template sensor copy to enable it:
``` yaml
- sensor:
    - name: "Frigate CPU use copy"
      unit_of_measurement: "%"
      state_class: "measurement"
      device_class: "temperature"
      state: >
        {{ states('sensor.docker_monitor_frigate_cpu_use') }}
```
